version: "3.1"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend

  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eshop
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    container_name: mydb

    volumes: 
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080
    depends_on:
      - "mydb"
    container_name: adminer
